fixtures:
  repositories:
    "xinetd": "git://github.com/puppetlabs/puppetlabs-xinetd"
    "concat": "git://github.com/puppetlabs/puppetlabs-concat"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    "rsync": "#{source_dir}"
